### PR TITLE
Now all close icon should look the same in all browsers

### PR DESCRIPTION
**Pull request by YaroslavOvdii**
@sofiiakvasnevska 
## Issue
https://github.com/Fliplet/fliplet-studio/issues/4773

## Description
Now all close icon should look the same in all browsers

## Screenshots/screencasts
Android 9 Native
Android 9 native

iOS Chrome
iOS chrome

iOS native
iOS native

macOS firefox
mac firefox

macOS safari
mac safari

Windows chrome
win chrome

Windows MS Edge 18
win edge18

Windows Firefox
win firefox

Windows MS IE 11
win ie11

Android 9 Chrome
Android 9 chrome

## Backward compatibility

This change is fully backward compatible.

## Notes
Using an SVG icon instead of the Unicode icon.

### CODE REVIEW

**Comment by tonytlwu** [comment]
@YaroslavOvdii It looks like the proportion for the "X" is too big compared to how it looks now. Can you correct them?

Before: image

After: 
image

Also, can you post screenshots for how it looks on tablets and desktop too?

**Comment by YaroslavOvdii** [comment]
@tonytlwu 
image
If it will look like that it will be okay or better find more bold SVG?

**Comment by tonytlwu** [comment]
@YaroslavOvdii Size looks correct now, but yes, the strokes need to be more bold.

**Comment by YaroslavOvdii** [comment]
@tonytlwu 
like that right?
image

**Comment by tonytlwu** [comment]
Perfect!

Also, can you post screenshots for how it looks on mobile, tablets and desktops?

**Comment by YaroslavOvdii** [comment]
@tonytlwu 
For the simple list, I've added a white SVG icon so it looked better.
If it is suitable for you I'll add a new commit with these changes.

Agenda
agenda lg
agenda md
agenda sm

Directory
dir lg
dir md
dir sm

Featured list
featured lg
featured md
featured sm

News
news lg
news md
news sm

Simple list
simple lg
simple md
simple sm

**Pull request merged**
