### PR TITLE
Agenda layout looks correctly on IE

### PR DESCRIPTION
**Pull request by MaksymShokin**
@sofiiakvasnevska

## Issue
Fliplet/fliplet-studio#5710

## Description
Position fixed does not seem to work in IE in this case. I changed to position relative.

## Screenshots/screencasts
IE

### CODE REVIEW

**Comment by tonytlwu** [comment]
@MaksymShokin You need screencast video(s) to show:

1. How does this work when there are and are not enough agenda items for vertical scrolling
1. How does this work in IE 11 versus non-IE 11 environments

**Comment by MaksymShokin** [comment]
@tonytlwu 
Everything seems to look fine.
lfd

**Comment by tonytlwu** [comment]
@MaksymShokin I mentioned vertical scrolling. You've shown me horizontal scrolling.

**Comment by MaksymShokin** [comment]
@tonytlwu 
Vertical scroll
ie-vertical

**Comment by MaksymShokin** [comment]
@tonytlwu 
Let's hold up this PR, I found similar issues in IE related to this.

**Comment by MaksymShokin** [comment]
@tonytlwu 
Now everything should work correctly

**Comment by tonytlwu** [comment]
@sofiiakvasnevska Could you let me know when this is on staging. There are a few tests I'd like to personally run.

**Pull request merged**
