### PR TITLE
Searches data correctly when cell contains a comma separated list of values

### PR DESCRIPTION
**Pull request by tonytlwu**
Ref. https://github.com/Fliplet/fliplet-studio/issues/4098

### CODE REVIEW

**Comment by tonytlwu** [comment]
@squallstar 6 😞 

I wanted to start building a small library of helper functions within the LFD component. It could just be a JS that gets included via `widget.json`. The question is how would I structure that JS file?

```js
LFD.Utils = (function () {
  function search () {
    // The patch I just added
  }

  return {
    search: search
  };
})()
```

And then the patch to this issue would just be for me to set up the function above and then use `LFD.Utils.search()` 6 times. It's a functionality that's low level enough such that people would/should never really need to tweak. And even if they do, they change custom code their own and not mess with the `.Utils` version.

Thoughts?

**Comment by tonytlwu** [comment]
@squallstar Actually, I just read how @angelnikolov did the work for the query parser and I think I'll go for:

```js
Fliplet.Registry.set('dynamicListUtils', function() {
  function search () {
    // The patch I just added
  }

  return {
    search: search
  };
});
```

Then each LFD layout JS file can add:

```js
DynamicList.prototype.Utils = Fliplet.Registry.get('dynamicListUtils');
```

**Comment by squallstar** [comment]
@tonytlwu yes, I was about to suggest to use the structure Angel used (which was proposed and reviewed by me)

**Comment by tonytlwu** [comment]
@angelnikolov Hi

**Comment by angelnikolov** [comment]
:D Heyy 🎉

**Comment by tonytlwu** [comment]
@angelnikolov Could you look into this issue `https://github.com/Fliplet/fliplet-studio/issues/4093` please?

j/k How're you doing lol

**Comment by angelnikolov** [comment]
Haha, I am on it! :D
I am good, thank you :)

**Comment by tonytlwu** [comment]
@squallstar I'm going to merge this. Will refactor this week.

**Pull request merged**
